server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql:///bbs
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      commit-on-return: true
mybatis:
    type-aliases-package: com.example.bbs.entity
    mapper-locations: classpath*:mapper/*.xml